name: flutterflow_theme
description: "flutterflow_theme is a Flutter package that provides a set of themes and styles for Flutter applications, designed to enhance the visual appeal and user experience. It includes customizable themes, typography, and color schemes that can be easily integrated into any Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  # assets_audio_player: 
  #   git:
  #     url: https://github.com/FlutterFlow/Flutter-AssetsAudioPlayer.git
  #     ref: 243f9533279b73fa9dae345cc96e5d7d84cac0ac
  # assets_audio_player_web: 
  #   git:
  #     url: https://github.com/FlutterFlow/Flutter-AssetsAudioPlayerWeb.git
  #     ref: cae7ceb6af99f4da1ec27136d312d0ef045c83d9
  assets_audio_player: ^3.1.1

  auto_size_text: ^3.0.0
  chewie: ^1.12.1
  dropdown_button2: ^2.3.9
  file_picker: ^10.3.6
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  font_awesome_flutter: ^10.8.0
  from_css_color: ^2.0.0
  google_fonts: ^4.0.4
  image_picker: ^1.2.1
  intl: ^0.20.0


  json_path: ^0.7.6
  mime_type: ^1.0.1
  page_transition: ^2.2.1


  photo_view: ^0.15.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  substring_highlight: ^1.0.33
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
